DROP TABLE IF EXISTS quotes;
CREATE TABLE quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author TEXT NOT NULL,
    quote TEXT NOT NULL
);